version: "3"
services:
  api_gateway:
    image: vx.kt.gh.api-gateway
    environment:
      - MONGO_HOST=mongo
      - USER_SERVICE_HOST=userservice
      - POST_SERVICE_HOST=guildpost
    ports:
      - 8080:8080
    depends_on:
      - userservice
      - guildpost
      - mongo
  
  userservice:
    image: vx.kt.gh.api-gateway
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
  guildpost:
    image: sp.jv.guild-post
    environment:
      - MONGO_HOST=mongo
    ports:
      - 8081:8080
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - 27017:27017

